services:
  ngnx:
    build: ./requirements/nginx
    image: ngnx:almeekel
    container_name: ngnx
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - almeekel
    depends_on:
      - wordpress

  db:
    build: ./requirements/mariadb
    image: db:almeekel
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - almeekel

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:almeekel
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - almeekel
    depends_on:
      - db

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/almeekel/data/wordpress

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/almeekel/data/db

networks:
  almeekel:
    driver: bridge
